version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: sourav.com
      #KC_HOSTNAME_PORT: 8080
      #KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_PROXY: 'edge'
      # more
      KC_PROXY_ADDRESS_FORWARDING: "true"
      PROXY_ADDRESS_FORWARDING: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      VIRTUAL_HOST: sourav.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: sourav.com
      LETSENCRYPT_EMAIL: sourav@gmail.com
    ports:
      - "8080"
    restart: always
    networks:
      - bpc_net
networks:
  bpc_net:
    external: true
